cam_model: Pinhole
cam_width: 1920
cam_height: 1200
scale: 1.0
cam_fx: 1007.934402
cam_fy: 1005.015553
cam_cx: 915.405452
cam_cy: 634.694653
cam_d0: -0.235962
cam_d1: 0.041613
cam_d2: 0.000377
cam_d3: 0.002262




# camera matrix
# 1075.976011 0.000000 639.859841
# 0.000000 1076.310320 360.682306
# 0.000000 0.000000 1.000000

# distortion
# 0.095776 -0.131002 0.000906 0.004022 0.000000
